all:
	$(MAKE) -C LT
	$(MAKE) -C modeC
	$(MAKE) -C LTE
	$(MAKE) -C Range
	$(MAKE) -C Divisor

.PHONY: clean 
clean:
	$(MAKE) -C LT clean
	$(MAKE) -C modeC clean
	$(MAKE) -C LTE clean
	$(MAKE) -C Range clean
	$(MAKE) -C Divisor clean
